### ISSUE TITLE
Fallout 4 - Index Controllers

### ISSUE THREAD

**Issue by Spinfusor99** [fholger/openvr_fsr#118]
Hi there.  Any way to incorporate the Index/Oculus fix that the CAS .dll has?

**Comment by fholger** [comment]
There is no need - the fix is obsolete.
All you need is a controller binding that is set to emulate Touch controllers, and it will work as is.

You can check your current binding by opening it in the SteamVR binding editor and look under "Legacy actions". If it's not set to emulate Oculus Touch, set it to do that and save the profile. You do need to have your controllers turned on before you launch the game.
