### ISSUE TITLE
open_fsr 2.0 sometimes does not work (IL-2)

### ISSUE THREAD

**Issue by BrziJoe** [fholger/openvr_fsr#125]
Hi Fholger. 
recently in IL-2 it is strange behavior of open_fsr. I tried to find what was different, and finally, the latest version open_fsr_v2.0 often works partially. It goes until first line of creating shader "Creating shader resource view for input texture 00000.....", and further log is empty. 

If I compare with older fsr version (v1.2), there are next lines in log like this:

"Texture has size 2896x3000 and format 28
Creating replacement sampler for 000001CB1AC882A0 with MIP LOD bias -0.378205
Creating replacement sampler for 000001CB1AC88AA0 with MIP LOD bias -0.378205..."

Often that part in version 2.0 comes when I shut down my game. 

The picture indeed looks sharper, but also enemy planes are more blended with surroundings in IL-2.
Is something changed in v2.0 what breaks now in that game?

PS: i put some spaces in logs, the second part comes only when I shut down my game!

[openvr_fsr_v2.0 (1) test.zip](https://github.com/fholger/openvr_fsr/files/7663406/openvr_fsr_v2.0.1.test.zip)

**Comment by fholger** [comment]
If you are just concerned about the log lines, that's not an issue. The write happens in a buffered way and lines only actually appear in the log file when a write flush happens. It is absolutely possible that this only happens when you quit the game. Earlier versions might have had an explicit flush at some point in the code, so they appeared to be written sooner. But again, this is totally fine and not a problem.

**Comment by BrziJoe** [comment]
I understand, thank you  I will close this issue.
