### ISSUE TITLE
List for verified games

### ISSUE THREAD

**Issue by DFOXpro** [fholger/openvr_fsr#13]
Hi FHolger

can you please enable the wiki of this project to document all tested games?

for example:

Game|Engine|dll location|extra notes|tested down to
---|---|---|---|---
Project Wingman|Unreal 4|%steam app / common% /Project Wingman/Engine/Binaries/ThirdParty/OpenVR/OpenVRv1_5_17/Win64/ |below balanced "small" text is unreadable|rx 480
DCS World|Custom?|%steam app / common% /DCSWorld/bin/ |below quality UI text is unreadable|rx 480

**Comment by tambe** [comment]
I have tested it in rfactor 2 and I have managed to get it to work, it looks great.

**Comment by fholger** [comment]
I have unlocked access to the Wiki, feel free to create the list as desired.

For input, the following games are confirmed *non-working* and can't work with the current approach:
- HL: Alyx (does not like to have its openvr_api.dll replaced)
- Star Wars Squadrons (does not like to have its openvr_api.dll replaced)
- Project Cars 2 (uses a custom openvr_api.dll that can't be replaced by this mod)
- Doom VFR (uses Vulkan, not DX11)
- MSFS 2020 (uses OpenXR, not OpenVR)

**Comment by teddybear082** [comment]
I tested as follows:

Working:

SkyrimVR

Tales of Glory

Outer Wilds VR mod - need to put in game folder / OuterWilds_Data / Plugins, otherwise it won't work.   Gained ~10 FPS and no ascertainable loss of quality with renderscale .70 and sharpeness .85

Risk of Rain 2 VR Mod - put into game folder / Risk of Rain 2_Data / Plugins

Partially Working:
Xplane 11 through Virtual Desktop/Quest/SteamVR - generates log file but does not appear to perform all the same steps as in logs above.

American Truck Simulator - generates log file but only the following (Virtual Desktop + Quest, OpenVR mode): 
Initializing hooks...
Requested interface FnTable:IVRSystem_021
Requested interface FnTable:IVRCompositor_026
Shutting down hooks..

Apparently Not Working:
PayDay2 - freezes when opening, does not start up


Also, it might be noted somewhere clearly to avoid questions that where connected with a Quest with a link cable and the game runs in the Oculus native runtime (e.g., Assetto Corsa, American Truck Simulator, Xplane 11 with Link cable, GTAV VR mod) this solution will not work (I think, unless I have that wrong - at least with me doing it in those games it did not generate the log file).

**Comment by kinemitor** [comment]
works in Subnautica
not work in Radial-G : Racing Revolved (game runs in flat mode)

**Comment by Nigh7Stalk3r** [comment]
So far of the games i've tested it works in 

Dirt Rally 2.0 (doesn't work in menu's only kicks in when it puts you in the cockpit at the start of the stage)
Car Mechanic Simulator VR
Blueplanet VR 
Zero Caliber VR
Asetto Corsa Competizione
House Flipper VR 
Medal Of Honor Above and Beyond
The Walking Dead Saints and Sinners

Doesn't work in 

ETS2
ATS
Creed Rise To Glory

Update with some more games.

**Comment by patientx** [comment]
Tested the 1st version and 
Works in : 
Boneworks 
Pavlov VR 
Elite Dangerous

**Comment by Redy1911** [comment]
works in ACC, AMS2 (visit ACC forum)

**Comment by jordanpucela** [comment]
> funciona en ACC, AMS2 (visite el foro de ACC)

How does ams2 work?  Because it doesn't work for anyone and even the creator has said that it doesn't work in that game, nor would it work.

**Comment by patientx** [comment]
Works in : 
Sniper Elite VR 
 but the overhead is so large at the standard res that to get the same performance as not using the mod you have to lower the scale to below 0.67 ... So basically useless ( ryzen 3600x - rx 480)

**Comment by tambe** [comment]
> works in ACC, AMS2 (visit ACC forum)

I have searched for that info. but i haven't been able to find it, would you kindly leave a link?

**Comment by fholger** [comment]
Please report future results on the Wiki page :)

https://github.com/fholger/openvr_fsr/wiki
