### ISSUE TITLE
FSR 2.0?

### ISSUE THREAD

**Issue by Elituz** [fholger/openvr_fsr#145]
FSR 2.0 is coming out and I was wondering if this was going to update to that

**Comment by SorceressLyra** [comment]
FSR 2.0 is a pretty different implementation of FSR that utilizes depth, motion vector and color buffers to generate an upscaled imagine with temporal coherence.

In order to add this, developers will have to integrate it into their games much like DLSS.

I'm unsure if it would be possible to do with a simple replacement of the openvr_api.dll, as it requires specific render buffers to be setup in engine.

Take what I say of course with a grain of salt, since FSR 2.0 isn't released to the public yet, so we are yet to know how the exact implementation will function.

**Comment by fholger** [comment]
Yeah, same boat as DLSS or Intel's upcoming XeSS - they require deep engine integration and can therefore not be added in a generic way. So to answer your question, no, FSR 2.0 will not be supported.

**Comment by DFOXpro** [comment]
If any here is the new official documentation about fsr2 https://github.com/GPUOpen-Effects/FidelityFX-FSR2
