### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by Patola** [fholger/openvr_fsr#33]
I understand Linux support would not be a priority -- even on Linux, almost all of the VR games available are actually Windows binaries running through Proton and using openvr_api.dll --, but would a Linux version (openvr_api.so) be feasible?

**Comment by fholger** [comment]
Theoretically? Yes. However, it's not something I can readily do. It would require a different hooking mechanism for Linux, and I don't currently have the necessary knowledge. It would also need to target Vulkan as a graphics API instead of D3D11, and that's also not something I'm sufficiently familiar with, yet.

For this to actually happen, it'd probably need someone else to do the work.

**Comment by stableversion** [comment]
There's no need. A tiny fraction of games support native Linux VR, it's a niche inside a niche. That said, this openvr fsr mod works perfectly for Linux proton games, the modification to get it running is the same. Also, there is currently a merge request in proton for "hacked in" fsr support, although not for VR, yet.
