### ISSUE TITLE
renderScale 1.00 breaks Elite Dangerous VR

### ISSUE THREAD

**Issue by rhylos** [fholger/openvr_fsr#9]
Elite Dangerous VR mode (tested with Odyssey) breaks to a 3D 2D type of 360' scene, when the Elite Dangerous graphics configuration is set to use an in game HMD setting higher than 1.0 in combination with openvr_fsr's renderScale is set to 1.00. 

Any value above 1.00 (1.00001) or below (0.99999) renders correctly, albeit with a lot of GPU overhead.

**Comment by fholger** [comment]
Did this happen when you changed the resolution in game? Did the issue persist when you restarted the game with the higher resolution already configured?

At first glance, I'd think this has to do with the game suddenly changing its render resolution due to your config change, and previous releases did not react to that change. You could try the latest release, as it should be able to deal with that situation.

**Comment by rhylos** [comment]
It did start upon in game change; however, persisted after full game restart and system reboot. I also was able to change the HMD value in game with no VR/3D issues if the renderScale was above or below 1.00.

**Comment by rhylos** [comment]
I retested with the 1.2 version released today and this issue does look to be resolved.

**Comment by fholger** [comment]
Ok, then it may still have resized its render texture at some point even after a fresh start. I'm assuming this is fixed, feel free to reopen if it happens again.
