### ISSUE TITLE
FSR + VRSS

### ISSUE THREAD

**Issue by DasaniSamurai** [fholger/openvr_fsr#93]
Are there any compatibility issues with these two pieces of software?

The scenario in my head is using FSR & VRSS with my G2 will give me the fullest advantage out of using the HMD
If I'm looking into a large map with plenty of objects/people to render, VRSS will disengage and I render at 0.77% res via FSR
If I'm in a small room with barely anything in the then VRSS kicks in and raises the SteamVR res setting so FSR's 0.77% becomes on par with a native 100% resolution image

**Comment by fholger** [comment]
I haven't tried, but from my understanding of VRSS, it happens transparently and is resolved before the image is ever submitted, so it should be completely transparent to FSR. However, this means that it will always render to the lowered render resolution, for which it may then decide to supersample pixels in the center. These will then effectively be averaged and resolved to the original lowered resolution before being submitted to SteamVR. Here, FSR will then pick it up and upsample the image.

**Comment by DasaniSamurai** [comment]
Oh, so the jist of your explanation is that vrss will work but fsr would ultimately nullify the visual enhancements but not the additional gpu load from vrss right?

**Comment by fholger** [comment]
No, it won't nullify it, but VRSS will work in reference to the lower render resolution enforced by FSR.

In essence, the way that VRSS works is that the game basically creates a multi-sampled rendertarget in its desired render resolution. This rendertarget then has storage for up to 8 samples per pixel, and VRSS will dynamically decide how many of those samples it will evaluate for the inner pixels, meaning that some pixels get super-sampled, i.e. sampled more than once. The samples are then resolved, i.e. averaged to create one final output value for their pixel. If FSR is active, this whole process will happen at a lower resolution than without it, which also means that you still save performance due to the lower render resolution and might actually give VRSS more headroom to work. But how well the final upscaled FSR image will look vs. using VRSS without it, I have no idea.

**Comment by DasaniSamurai** [comment]
From what I understand of what you said, the end result is that the end user ends up with three middle grounds.
FSR's designated resolution, the resolution set in SteamVR that FSR upscales to and VRSS which operates off of the FSR set res and not the SteamVR option.

**Comment by DasaniSamurai** [comment]
My primary motive for this topic is to provide documentation for people in the future to delve further into

**Comment by kantsche** [comment]
Best would be like 50% resolution at the borders of the image 80-90% in the center and then upscale. But that needs to be on a layer deeper in the game engine where VRSS come into play right?
